services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_BACKEND_URL=http://localhost/api
    networks:
      - app-network
    depends_on:
      - caddy

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "9000:9000"
    networks:
      - app-network
    depends_on:
      - db

  caddy:
    container_name: caddy
    image: caddy:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./backend:/var/www/html
      - ./Caddyfile:/etc/caddy/Caddyfile
    networks:
      - app-network
    depends_on:
      - backend

  db:
    container_name: db
    image: bitnami/postgresql:16.3.0
    platform: linux/amd64
    ports:
      - 5435:5432
    restart: always
    volumes:
      - db-data:/bitnami/postgresql
    environment:
      - POSTGRESQL_DATABASE=postgres-database
      - POSTGRESQL_USERNAME=postgres-username
      - POSTGRESQL_PASSWORD=postgres-password
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
