services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - ./frontend/node_modules
    environment:
      - VITE_API_BASE_URL=http://caddy/api
    restart: unless-stopped
    networks:
      - app-network
    depends_on:
      - caddy

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "9000:9000"
    networks:
      - app-network
    depends_on:
      - db

  caddy:
    image: caddy:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./backend:/var/www/html
      - ./Caddyfile:/etc/caddy/Caddyfile
    networks:
      - app-network
    depends_on:
      - backend

  db:
    image: bitnami/postgresql:16.3.0
    platform: linux/amd64
    ports:
      - 5432:5432
    restart: always
    volumes:
      - db-data:/bitnami/postgresql
    environment:
      - POSTGRESQL_DATABASE=${POSTGRESQL_DATABASE}
      - POSTGRESQL_USERNAME=${POSTGRESQL_USERNAME}
      - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
